version: '3'

services:
  library:
    image: mysql:5.7
    container_name: library
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tiger
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=tiger
      - MYSQL_DATABASE=library
      - TZ=UTC
    volumes:
      - library:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--max_allowed_packet=1073741824' ]

volumes:
  library:
