spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=yes&serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: tiger
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
#            client-id: e475671da6e0d9156c91
#            client-secret: 3cc11749c4247bb0e46a05dbca3fe0f6f605e34f
            client-id: a887b85fe5b107d04b2d
            client-secret: 9c9fdaa99cdbf1da79e17ad156f0997683e253fe
            scope: user

interpark:
  url: http://book.interpark.com/api/search.api
  key: 3EC5D629CEC08F5BCA2D9A06828BEA9DFD97B235FE96531999FB084FFA68CBEA
  output: json
  queryType: isbn

logging:
  level:
    web: debug
    kr.codesquad.library: debug
    org.hibernate.SQL: debug

app:
  redirectUrl: http://localhost:3000

---
spring:
  profiles: prod
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH_CLIENTID}
            client-secret: ${OAUTH_SECRET}
            scope: user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(8pvdAxQRgIuKhtBrCfJVzn8DSb1UelH14Lrej4lzH45axRUnbph6unUK8O96oSANhxEwd0vgXDhGKZHpLKG9gMYbeDV4r/VgfFjHlL6r69vu4j19H+SX6mUp9rokcTF7+H50DxsFJhU=)
    username: ENC(71gUI9lQ/y/BFvIU5GQsqQ==)
    password: ENC(WBG3Dt2Mu/bxWIoOQqXW3A/gMD33Dw5d)
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

interpark:
  url: http://book.interpark.com/api/search.api
  key: ENC(lUMKI+3wRsN1uviJdT9s4oZWH58eSHVViAkXOrCK0pApnolu4Z4GCFHAsd0z+5uUw71p3i/6xPRORAb+hj+VpEraz65H4/PSlP7AiwptG10=)
  output: json
  queryType: isbn

logging:
  level:
    web: debug
    kr.codesquad.library: debug
    org.hibernate.SQL: debug

app:
  redirectUrl: http://librarycodesquad.com

