spring:
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        exclude: env,beans
        include: "*"

---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=yes&serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: tiger
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    web: debug
    com.codesquad.issue: debug
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
