version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x /server/gradlew
      - /server/gradlew bootJar
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    - /server/build/libs/*.jar
    - appspec.yml
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
